### PR TITLE
Update formula according to Homebrew guidelines

### PR DESCRIPTION
**Pull request by dominiklohmann**
As discussed in koekeishiya/chunkwm#95.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
Before merging: still need to update this to 0.3.0, missed that release.

**Comment by crisidev** [comment]
Thanks a lot!

**Comment by crisidev** [comment]
@dominiklohmann I have reverted the change since it does not work for me. I will take a look as soon as I have time and figure out if is a problem I only have or if it can affect other users.

**Comment by dominiklohmann** [comment]
The plugin path changed to something more in line with homebrew-core guidelines. You will have to change it in your config.

**Comment by crisidev** [comment]
Ok. I think that was my problem. I will reapply the PR  and update the README to give other people the chance to fix the problem too.

Sorry if I reverted, but I was really in hurry today and I did not want to break compatibility.

Also the codesigning is not working for me.

I create the certificate, trusted it, codesigned the binary, but it still asks for permissions. I also did it as sudo. Any idea what it can be?

**Comment by dominiklohmann** [comment]
With the certificate, you won't have to re-apply permissions if the binary changes. You still have to trust it once.

sudo is not needed and should not be used here.

I update like this:

```
brew services stop chunkwm
brew reinstall --HEAD chunkwm
codesign -fs my-cert path/to/chunkwm
brew services start chunkwm
```

**Pull request merged**
